spring.application.name=auth-service
server.port=8081

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=authservice
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health,info,loggers
management.endpoint.health.show-details=always

info.app.name=Auth Service
info.app.version=1.0.0
info.app.description=Job Application Tracker - Auth Service