spring.application.name=auth-service
server.port=5432

spring.datasource.url=jdbc:postgresql://localhost:5432/JobTracker
spring.datasource.username=emmanuelmichel
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=auth_service
spring.jpa.show-sql=true

jwt.secret=OS8YpP0gy(:lczJ2H+[rCC2VTA@Wy^6Cy:evlIBZ6}U
jwt.expiration-ms=86400000