spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://db.zrxbzqwdteenwrqmpanp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=n3hE0R7Q1HdArOjn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=authservice
spring.jpa.show-sql=true

jwt.secret=OS8YpP0gy(:lczJ2H+[rCC2VTA@Wy^6Cy:evlIBZ6}U
jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health,info,loggers
management.endpoint.health.show-details=always

info.app.name=Auth Service
info.app.version=1.0.0
info.app.description=Job Application Tracker - Auth Service